version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: .
    binary: treebuilder

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: nmdra
    name: treebuilder
  footer: |
    ---

    Released by [GoReleaser](https://goreleaser.com).

    Built with ❤️ by Nimendra — [blog.nimendra.xyz](https://blog.nimendra.xyz)
